import "../styles/globals.css";
import { Provider } from "react-redux";
import store from "../provider/store";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  return (
    <div style={{ backgroundColor: "white" }}>
      {/* <Head>
        <title>Web3Hacks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <Provider store={store}>
        <Component {...pageProps} />
      </Provider>
    </div>
  );
}

export default MyApp;
