import "../styles/globals.css";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import store, { persistor } from "../provider/store";
import { QueryClient, QueryClientProvider } from "react-query";
import Head from "next/head";
import "react-notifications-component/dist/theme.css";
import { ReactNotifications } from "react-notifications-component";


const queryClient = new QueryClient();

function MyApp({ Component, pageProps }) {
  return (
    <div style={{ backgroundColor: "white" }}>
      {/* <Head>
        <title>Web3Hacks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <QueryClientProvider client={queryClient}>
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <ReactNotifications />
            <Component {...pageProps} />
          </PersistGate>
        </Provider>
      </QueryClientProvider>
    </div>
  );
}

export default MyApp;
