import "../styles/globals.css";
import { Provider } from "react-redux";
import store from "../provider/store";
import { QueryClient, QueryClientProvider } from "react-query";
import Head from "next/head";
import "react-notifications-component/dist/theme.css";
import { ReactNotifications } from "react-notifications-component";

const queryClient = new QueryClient();

function MyApp({ Component, pageProps }) {
  return (
    <div style={{ backgroundColor: "white" }}>
      {/* <Head>
        <title>Web3Hacks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <QueryClientProvider client={queryClient}>
        <Provider store={store}>
          <ReactNotifications />
          <Component {...pageProps} />
        </Provider>
      </QueryClientProvider>
    </div>
  );
}

export default MyApp;
